# Generated by Django 5.2.3 on 2025-07-01 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, message='Category name must be in the range of 3 -50 characters'), django.core.validators.RegexValidator('^\\S+$', message='Category cannot start with a whitespace')]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Title must be in the range of 3-100 characters'), django.core.validators.RegexValidator('^\\S+$', message='Title cannot start with a whitespace')]),
        ),
    ]
